version: '3.8'
services:
  llmchat2api:
    build: .
    ports:
      - '8000:8000'
    environment:
      - CHATRAPPER_TOKEN=${CHATRAPPER_TOKEN}
    volumes:
      - ./conversations.db:/app/conversations.db
